name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  release:
    types:
      - created

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      ACTIONS_ALLOW_UNSECURE_COMMANDS: true
    steps:
    - uses: actions/checkout@v4
    - name: Fetch all history for all tags and branches
      run: git fetch --prune --unshallow
    - name: Setup Node.js environment
      uses: actions/setup-node@v4
      with:
        node-version: '18'
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 7.0.x
    - name: Install GitVersion
      uses: gittools/actions/gitversion/setup@v1.2.0
      with:
          versionSpec: '5.x'
    - name: Use GitVersion
      id: gitversion # step id used as reference for output values
      uses: gittools/actions/gitversion/execute@v1.2.0
    - run: |
        echo "SemVer: ${{ steps.gitversion.outputs.semVer }}"
    - run: npm install
    - name: Install dependencies
      run: dotnet restore
    - name: Run generator
      run: dotnet run -c release --project ./src/MimeDb.Generator -- ./node_modules/mime-db/db.json ./src/MimeDb/MimeDb.cs
    - name: Build
      run: dotnet build -c Release --no-restore
    - name: Test
      run: dotnet test --verbosity normal
    - name: Pack
      run: |
        dotnet pack --no-restore /p:PackageVersion=${{ steps.gitversion.outputs.semVer }} -o ./artifacts
    - name: Publish artifacts
      uses: actions/upload-artifact@v4
      with:
        name: artifacts
        path: ./artifacts
    - name: Publish NuGet
      if: github.event_name == 'release' && github.event.action == 'created'
      run: dotnet nuget push ./artifacts/*.nupkg -k ${{ secrets.NUGET_PUSH }} -s https://api.nuget.org/v3/index.json --skip-duplicate
      
      
